### ISSUE TITLE
Random crash while scanning image

### ISSUE THREAD

**Issue by ashishgupta2510** [BlinkReceipt/blinkreceipt-android#10]
I got soft crash while scanning image and I did not get sufficient logs to know the reason, I get only "A/libc: Fatal signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0x75d968409c in tid 14484 (RecognizerHandl), pid 14294" 
Please Help me out.

Thank you

**Comment by pequots34** [comment]
Can you please share the image your trying to scan
