### ISSUE TITLE
ScanResult is only returning data from the first image when calling `.recognize` with multiple Bitmaps

### ISSUE THREAD

**Issue by cxrod** [BlinkReceipt/blinkreceipt-android#11]
Hi, I'm trying to get data from a long receipt in 2 images using the recognize function of the Recognizer class, but is only retrieving the info of the first image.

I'm using version 1.3.6 of the library.

This is my code
```
            Bitmap[] bitmaps = getBitmaps(stringUris);
            Recognizer.getInstance(reactContext).initialize(getOptions());
            Recognizer.getInstance( reactContext ).recognize(new SimpleRecognizerCallback() {

                @Override
                public void onRecognizerDone(@NonNull final ScanResults results, @NonNull final Media media ) {
                    super.onRecognizerDone( results, media );

                    promise.resolve(parseResultToJson(results));
                }

                @Override
                public void onRecognizerResultsChanged(@NonNull RecognizerResult recognizerResult) {
                    super.onRecognizerResultsChanged(recognizerResult);
                    promise.resolve(parseRecognizerToJson(recognizerResult));
                }
            }, CameraOrientation.ORIENTATION_PORTRAIT, bitmaps) ;
```
This is a screenshoot of the debugger with 2 bitmaps.
![image](https://user-images.githubusercontent.com/16138018/92139590-530f6400-ede6-11ea-99d2-953b8310348f.png)

I will attach the receipt images and the JSON with de result.

[Image 1](https://user-images.githubusercontent.com/16138018/92147853-0df12f00-edf2-11ea-9ef3-162a594d9664.jpeg)

[Image 2](https://user-images.githubusercontent.com/16138018/92147839-0a5da800-edf2-11ea-9ee2-74f40dd0b86c.jpeg)

[result's JSON](https://github.com/BlinkReceipt/blinkreceipt-android/files/5170239/result.txt)

**Comment by pequots34** [comment]
@cxrod This is not a general use api. You should not be using the recognizer directly as you should be processing OCR results through the recognizer view. in 1.3.7 this class will no longer be visible.

**Comment by cxrod** [comment]
@pequots34 ok, Do you have any documentation about it? Im creating a native module on my react native app, so Im al  ready have the camera UI cover and I just need to process the images from the URIs.

Thanks for your time.
Regards

**Comment by pequots34** [comment]
There wouldn't be any documentation as its still in development. The release notes will reflect the change, but essentially you will not longer be able to call into Recognizer class ( Recognizer.getInstance(reactContext ) ). If its react native you will need to build the activity and or fragment in native code ( java / kotlin ) and use the recognizer view that will provide the camera interface.

**Comment by pequots34** [comment]
Here is a sample.

https://github.com/BlinkReceipt/blinkreceipt-android/tree/master/blinkreceipt-demo/BlinkReceiptCustomScan
