### ISSUE TITLE
cannot find a way to seek for duplicate receipt

### ISSUE THREAD

**Issue by lavi-moolchandani** [BlinkReceipt/blinkreceipt-android#13]
I am using the android sdk and currently developing an app which requires the receipts to be scanned once only, now I saw the detect_duplicate flag in the blink receipt APIs and want to implement that in the android app as well, is there any way to detect duplicate from the SDK as well.

**Comment by pequots34** [comment]
You can set it on the scan options.

ScanOptions.newBuilder()
                .detectDuplicates(true)
                .build();
