### ISSUE TITLE
SdkNotInitializedException The SDK has not been initialized, make sure to call BlinkReceiptSdk.initialize() first.}

### ISSUE THREAD

**Issue by juanchiquizab** [BlinkReceipt/blinkreceipt-android#41]
Hi,
I downloaded the project I put my test key I compile the BlinkReceiptCustomScan module and it gives me this error when I go to CameraActivity

SdkNotInitializedException{, isNativeLibraryLoaded=false, nativeError=null, message=com.microblink.SdkNotInitializedException: The SDK has not been initialized, make sure to call BlinkReceiptSdk.initialize() first.}

![image](https://user-images.githubusercontent.com/107698678/181635302-c950ea41-82d9-4034-90ba-950c56e011e5.png)

v 1.5.9
Thank you

**Comment by pequots34** [comment]
Does the package name of your application match the generated license key from the development portal?
