### ISSUE TITLE
Identify images from different receipts

### ISSUE THREAD

**Issue by ErManishPatiyal** [BlinkReceipt/blinkreceipt-android#42]
Hi Team

I would like to know if there is a way to know if images sent to blink receipt sdk belongs to different receipts. So that we can notify user that they have shared receipts of a different shop. 

We are using following method 
 ```
 public void recognize(@NonNull ScanOptions var1, @NonNull RecognizerCallback var2, @NonNull Bitmap... var3) {
        this.recognize(var1, var2, (CameraOrientation)null, var3);
    }
```
What happen now is that user is adding receipts of multiple stores and in the result we are getting a mix result of both the stores and that is not useful

**Comment by GeekRishabh** [comment]
@ErManishPatiyal  Yes But you need to handle that on your app end itself. The SDK returns the object that contains retailer's name and information

**Comment by ErManishPatiyal** [comment]
What if two images are of 2 different retails, which retail store will be picks, first receipts or second receipt. Is there any flag in the return data you can add to inform about multiple receipts

**Comment by pequots34** [comment]
See @ErManishPatiyal comments :)
