### ISSUE TITLE
Image cordinates of items identified by SDK

### ISSUE THREAD

**Issue by ErManishPatiyal** [BlinkReceipt/blinkreceipt-android#43]
As an addition can we have the item cordinates on the image of list. We need to somhow highlight the items of the receipt and get them rectified by the user.[Requirement](https://drive.google.com/file/d/1OCoSOvdZPgfCovUmOWa2tvxYNbei9Qt2/view?usp=sharing)

**Comment by pequots34** [comment]
We currently don't support sending these data points back through the SDK. Will pass this along to our product team. Thank you
