### ISSUE TITLE
Missing values that are available in Blink Receipt Web Api

### ISSUE THREAD

**Issue by vtn-dev-manish** [BlinkReceipt/blinkreceipt-android#46]
The webapi of from Blink contains the following additional information:
**"is_blurry": false,
"is_receipt": true,
"is_screen": false,**
How can we get these in android and IOS?

We do have  "raw_text": "raw ocr text" 

```
@Override
public void onRecognizerResultsChanged(@NonNull RecognizerResult result) {
if ( result instanceof OcrRawResult ) {
OcrRawResult ocrRawResult = (OcrRawResult) result;
}
}
```

**Comment by dpanzer** [comment]
Hi @vtn-dev-manish - on iOS you can access these properties by implementing your own custom view controller and then in the callback for when the user snaps a picture, we provide a `BRFrameAttributes` object that contains these properties. The guide for implementing a custom camera controller is here: https://blinkreceipt.github.io/blinkreceipt-ios/custom-camera-controller.html and the specific method is this: [userSnappedPhotoOnReady](https://blinkreceipt.github.io/blinkreceipt-ios/Classes/BRCameraViewController.html#/c:objc(cs)BRCameraViewController(im)userSnappedPhotoOnReady:)

@pequots34 Can provide guidance for Android

**Comment by pequots34** [comment]
@vtn-dev-manish when you get a picture with the recognizer view you will get a Take Picture Result, which will have those properties.

captureFrame.setOnClickListener(v -> recognizerView.takePicture(new CameraCaptureListener() {

            @Override
            public void onCaptured(@NonNull BitmapResult results) {
                if (results instanceof TakePictureResult) {
                    TakePictureResult picture = (TakePictureResult) results;
                }

                recognizerView.confirmPicture(results);
            }

            @Override
            public void onException(@NonNull Throwable e) {
            }

        }));

**Comment by vtn-dev-manish** [comment]
Is there a way I can get these values in 
` override fun onRecognizerDone(results: ScanResults, media: Media) {`

As I need to know these values for images that are selected by user. Can we have these values in ScanResults object

**Comment by pequots34** [comment]
its currently only available when you take a picture.

**Comment by vtn-dev-manish** [comment]
Can we expect it to be in the next update?

**Comment by pequots34** [comment]
no this is not currently a feature we support, but will pass this along to our product team.
