### ISSUE TITLE
NDK crashes in cameraSdk  reported on playstore

### ISSUE THREAD

**Issue by vtn-dev-manish** [BlinkReceipt/blinkreceipt-android#55]
![Screenshot from 2023-05-05 10-59-56](https://user-images.githubusercontent.com/57625844/236383832-f49941b6-b081-42e2-9ddc-1a892e84f4f6.png)

**Comment by pequots34** [comment]
Are you able to share additional information regarding the device and the state at the time of the crash

**Comment by vtn-dev-manish** [comment]
I am sharing 3 reported issues on playstore in this [link](https://drive.google.com/file/d/1YD_8ZmILluv3w12_07OyG3mFYT8z3o_V/view?usp=sharing)

**Comment by pequots34** [comment]
@vtn-dev-manish, we weren't able to reproduce. Closing this issue for now as we have plans in H2 to evaluate CamerX as a replacement for our current camera experience.
