### ISSUE TITLE
ocrConfidence is always 0.0

### ISSUE THREAD

**Issue by gurjindersinghkhalsa** [BlinkReceipt/blinkreceipt-android#7]
I am getting ocrConfidence 0.0 everytime from below method
ScanResults results = data.getParcelableExtra(IntentUtils.DATA_EXTRA);
        results.ocrConfidence();

**Comment by pequots34** [comment]
We are looking into this issue. Thank you

**Comment by pequots34** [comment]
This has been addressed in the latest version of the SDK.
