### ISSUE TITLE
No scan result found when we take an image from gallery

### ISSUE THREAD

**Issue by chanchal12** [BlinkReceipt/blinkreceipt-android#8]
When we take an image from gallery. No scan result found. Can you help in this, its not working in demo project.

**Comment by pequots34** [comment]
Please visit https://microblink.com/signup to register a Microblink developer account. Once you have done that you can use the demo code as working examples. We don't publish the demo key as of now, which is why you don't get product results.

**Comment by chanchal12** [comment]
I have create an account and using demo license key but scanResult return null value.

**Comment by pequots34** [comment]
you won't be able to put the demo license in the sample code as the license is tied to your package name. You will need to port the demo code into your project that matches the license key registered

**Comment by chanchal12** [comment]
I have already use the demo key in my demo project. But not find the
scanResult is always return null.

**Comment by pequots34** [comment]
Can you post the receipt you are trying to scan. Also, try scanning on the static scan project as well.

**Comment by chanchal12** [comment]
In static scan it's working fine but in direct api when I select it from
gallery it's not return the scanResult.

Please find attached invoice.

**Comment by chanchal12** [comment]
Can we use both camera and gallery option in static scan demo project.

Thanks
Chanchal Kumar

**Comment by pequots34** [comment]
I don't see the attached receipt.

**Comment by chanchal12** [comment]
PFA

**Comment by pequots34** [comment]
Still don't see the attachment.

**Comment by chanchal12** [comment]
I have already attached invoice , have you any alternative like WhatsApp no
so I can send you invoice.

Thanks

**Comment by chanchal12** [comment]
In static scan it's working fine but in direct api when I select it from
gallery it's always return the scanResult is null.

PFA

![Invoice 1](https://user-images.githubusercontent.com/14177687/54579475-a098e500-4a29-11e9-98b7-747c2eb48525.jpeg)
![invoice2](https://user-images.githubusercontent.com/14177687/54579476-a098e500-4a29-11e9-89d1-29b86b6b8a70.jpeg)

**Comment by pequots34** [comment]
I was able to scan data from the direct api for these given receipts using the demo project
