### ISSUE TITLE
Need to save image while capturing it from camera.

### ISSUE THREAD

**Issue by chanchal12** [BlinkReceipt/blinkreceipt-android#9]
In BlinkReceiptStatic scan Is there any way to save images mobile storage.

**Comment by pequots34** [comment]
ScanOptions.newBuilder()
                .retailer( Retailer.UNKNOWN )
                .frameCharacteristics( FrameCharacteristics.newBuilder()
                        .storeFrames( true )
                        .externalStorage(true )
                        .build() )
                .edgeDetectionConfiguration(  new EdgeDetectionConfiguration() )
                .logoDetection( true )
                .build();

storeFrames and externalStorage in the frame characteristics class allows you to control where frames are stored. Depending on the OS version you will need to handle the file provider and access yourself. https://developer.android.com/training/secure-file-sharing/setup-sharing

**Comment by chanchal12** [comment]
Hi Christopher,

I am able to save the image but not fond the path. Can you help me that
which pattern are you using to capture the image.

Thanks,
Chanchal
