### ISSUE TITLE
BlinkSDK Enhanced UX get stuck when all chips are disabled

### ISSUE THREAD

**Issue by vtn-dev-manish** [BlinkReceipt/blinkreceipt-android#97]
If we run the new UI with all these values disabled (false) the app UI gets freezed at the scanning screen.

Data Chips: 
.scanCharacteristics(
        new ScanCharacteristics.Builder()
            .date(boolean)
            .merchant(boolean)
            .total(boolean)
            .build())

.onDeviceOcr())(boolean)

**Comment by pequots34** [comment]
Hey, @vtn-dev-manish, can you reproduce this on the demo app? 
https://github.com/BlinkReceipt/blinkreceipt-android/tree/master/blinkreceipt-demo/BlinkReceiptStaticScan

Can you please post a video of the experience?

**Comment by vtn-dev-manish** [comment]
Hi @pequots34, I tried your sample mentioned above and just changed the 
.date(false)
.merchant(false)
.total(false)

This got me the issue on your sample as well. I was able to click the picture but after that all buttons are disabled making the app look freezed, I can go back but that will not help. Sharing the video link with you
https://drive.google.com/file/d/1962hHwd4rF6V8tiApHYOxaT3odM0hJQe/view?usp=sharing

**Comment by pequots34** [comment]
@vtn-dev-manish, this will be fixed in SDK version 1.8.5. Thanks
