### ISSUE TITLE
BlinkSDK onDeviceOcr() returns false even when set to true using BlinkReceiptSdk.onDeviceOcr(true)

### ISSUE THREAD

**Issue by vtn-dev-manish** [BlinkReceipt/blinkreceipt-android#99]
BlinkSDK onDeviceOcr() returns true even when set to false using BlinkReceiptSdk.onDeviceOcr(false)

During our usage of the feature to enable and disable BlinkSDK onDeviceOcr(), we observed that the intended behavious is not shown by the method call BlinkReceiptSdk.onDeviceOcr(false). It always remains true even when called with false value.

Also in the latest sdk version the debug(value) function is removed and in the implementation of onDeviceOcr() you have checked its value which will always navigate to else condition.

`public static boolean onDeviceOcr() {
        if (debug) {
            return onDeviceOcr;
        } else {
            return VERSION.SDK_INT >= 23 && cpuPowerIndex >= 35.0F;
        }
    }`

**Comment by pequots34** [comment]
This will be addressed in 1.8.6
